---
# tasks file for talkmeup

- name: Git clone the application files
  git:
    repo: 'https://github.com/du6/talkmeup.git'
    dest: "{{ home_path }}"

- name: Manually creating the initial virtualenv
  command: "virtualenv -p python3.5 {{ venv_path }}"

- name: Updating pip
  pip:
    name: pip
    extra_args: --upgrade
    virtualenv: "{{ venv_path }}"

- name: Installing requirements
  pip: 
    requirements: "{{ app_path }}/requirements.txt"
    virtualenv: "{{ venv_path }}"

- name: Django migrate
  django_manage: command=migrate app_path={{ app_path }} virtualenv={{ venv_path }}

- name: Copying the upstart file
  command: "cp {{ app_path }}/scripts/talkmeup.conf /etc/init/talkmeup.conf"
  become: true

- name: Starting the server
  service:
    name: talkmeup
    state: started