---
# tasks file for talkmeup

- name: Copying the application files
  copy:
    src: /Users/yuelindu/Projects/aws/talkmeup/talkmeup
    dest: /home/ec2-user/
    owner: ec2-user
    group: ec2-user
    mode: u=rwx,g=rx,o=rx

- name: Manually creating the initial virtualenv
  command: "virtualenv -p python3.5 {{ venv_path }}"

- name: Updating pip
  pip:
    name: pip
    extra_args: --upgrade
    virtualenv: "{{ venv_path }}"

- name: Installing requirements
  pip: 
    requirements: "{{ app_path }}/requirements.txt"
    virtualenv: "{{ venv_path }}"

- name: Django migrate
  django_manage: command=migrate app_path={{ app_path }} virtualenv={{ venv_path }}

- name: Copying the upstart file
  copy:
    src: /Users/yuelindu/Projects/aws/talkmeup/talkmeup/scripts/talkmeup.conf
    dest: /etc/init/talkmeup.conf
    owner: root
    group: root
    mode: 0644

- name: Starting the server
  service:
    name: talkmeup
    state: started